name: publish
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'dry-run mode'
        required: false
        default: false
        type: boolean
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  id-token: write
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          CI: true
        run: npm run build -- --ci

      - name: Publish to npmjs.com
        run: npm run publish -- --ci ${{ github.event.inputs.dry_run == 'true' && '--dry-run' || '' }}
        env:
          CI: true