name: Publish Packages to npmjs
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run?'
        required: false
        default: false
        type: boolean
permissions:
  id-token: write
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          registry-url: 'https://registry.npmjs.org'
          
      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: packages/**/lib
          key: build-${{ runner.os }}-${{ github.run_attempt }}
          restore-keys: |
            build-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          CI: true
        run: npm run build -- --ci --run-build

      - name: Publish to npmjs.com
        run: npm run publish -- --ci --provenance ${{ github.event.inputs.dry_run == 'true' && '--dry-run' || '' }}
        env:
          CI: true