name: Update Snapshots
on:
  workflow_dispatch:
    inputs:
      update_snapshots:
        description: 'Force update of snapshots?'
        required: true
        default: false
        type: boolean
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          CI: true
        run: npm run build -- --ci

      - name: Restore Playwright cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright
          restore-keys: ${{ runner.os }}-playwright

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run tests
        env:
          CI: true
        run: npm test -- --ci ${{ github.event.inputs.update_snapshots == 'true' && '--update-snapshots' || '' }}

      - name: Commit and push snapshot changes
        continue-on-error: true
        run: |
          git fetch origin
          git add ./packages/**/tests/snapshots
          if [[ -n $(git status -s) ]]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git commit -m "add: github-runner snapshots"
            git push --force-with-lease
          fi